disabled_rules: # rule identifiers to exclude from running
  - multiple_closures_with_trailing_closure
  - todo
  - leading_whitespace
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - empty_count
  - array_init
  - force_unwrapping
  - empty_parameters
  - closure_spacing
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - overridden_super_call
  - weak_delegate
  - closing_brace
  - opening_brace
  - return_arrow_whitespace
  - trailing_semicolon
  - statement_position
  # Find all the available rules by running:
  # swiftlint rules
included:
  - PhotoLooker
excluded:
  - Pods
# configurable rules can be customized from this configuration file
trailing_semicolon: error
empty_count: error
closing_brace: error
opening_brace: error
return_arrow_whitespace: error
statement_position: error
colon: error
comma: error
force_cast: error
force_try:
  severity: warning
line_length: 150
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 450
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length:
    error: 2
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
warning_threshold: 7
